### ISSUE TITLE
Architecture Documentation disappeared 

### ISSUE THREAD

**Issue by csalch-indeed** [depscloud/deps.cloud#76]
As far as I can tell the architecture documentation is no longer visible on the public site. Was it's removal deliberate? Is there a replacement planed?

**Comment by mjpitz** [comment]
@csalch-indeed - I removed it from the site because there's now an `ARCHITECTURE.md` file in the repo and a lot of the content was duplicated over and the site felt like the wrong place for it: https://github.com/depscloud/depscloud/blob/main/ARCHITECTURE.md

**Comment by csalch-indeed** [comment]
Ahh ok, I had missed that. Thanks

**Comment by mjpitz** [comment]
No worries. That was more of a recent change to align with how I saw some other communities doing it. I also think it helped clean up the docs a bit more. One thing I haven't had a chance to port yet is the data model.
